rahuldkjain/github-profile-readme-generator

src/pages/index.css
src/pages/index.js

* Added ability to download the readme generated as a file

feat: Added the ability to download the readme as a file

---

src/constants/skills.js

Added new icons:
- linux
- redux
- webpack
- express

Added new icons

---

src/components/markdown.js
src/components/markdownPreview.js
src/components/social.js
src/pages/index.js

This is my first public contribution and I hope it helped! 😄

Add Dribbble, Behance, Medium, & Youtube input box in social

---

src/pages/index.js

fix: trim data values before generate

---

src/components/markdownPreview.js
src/components/skills.js
src/constants/skills.js
src/pages/index.css
src/pages/index.js
src/utils/validation.js

- add tooltip text in `skills`
- add github-username validation
- add icon for preview and markdown

add: tooltip, fix: github-validation

---

src/pages/index.js

fix: make hide download button on preview

fix: issue #21

---

src/components/markdown.js
src/components/markdownPreview.js
src/components/social.js

Resolves https://github.com/rahuldkjain/github-profile-readme-generator/issues/24

[FIX]: StackOverflow Broken URL

---

src/components/addons.js
src/components/markdown.js
src/pages/index.js
src/utils/validation.js
src/utils/workflows.js

Fixed typo in isMediumVaid function #44

[fix]: typo in isMediumVaid function

---

src/constants/skills.js

Comment only if changes needed in the current PR or if there are any more increments to the current skills.

📝 Added categories, skills & icons 🔗

---

src/constants/skills.js

Added
- Ionic -> Mobile Development
- Hugo -> static site generator
- CanvasJS -> Data Visualization
under #62

Added : ionic,hugo and canvas skills

---

src/constants/skills.js

Added:  
- MariDB
- Objective-C
- Clojure
- Rust
- Haskell
under #62

Added: Few skills in Database and Language category

---

README.md
gatsby-config.js
src/components/addons.js
src/components/header.js
src/components/markdown.js
src/components/markdownPreview.js
src/markdown-pages/about.md
src/markdown-pages/addons.md
src/markdown-pages/support.md
src/pages/index.js
src/templates/blogTemplate.js
src/utils/validation.js

Just a minor typo fix: `Github` -> `GitHub`.

Fix GitHub spelling

---

src/components/social.js

Updated social.js

---

src/components/markdown.js

Updated markdown.js

---

src/components/markdownPreview.js

Updated markdownPreview.js

---

src/pages/index.js

Updated index.js

---

src/pages/index.css

Minor: CSS change to show names of skills on hover for smaller desktops

---

src/constants/skills.js

https://github.com/rahuldkjain/github-profile-readme-generator/issues/78

Skills qtk, wt, xw-widgets added and png to svg skills

---

src/pages/index.css
src/styles/tailwind.css
src/templates/blogTemplate.js

Sir, please check in case of any error please suggest me.

Removed unnecessary comments

---

src/components/markdown.js
src/components/markdownPreview.js
src/components/social.js

Fix for the issue https://github.com/rahuldkjain/github-profile-readme-generator/issues/97

fix dsa  social links

---

src/components/addons.js
src/components/markdown.js
src/components/markdownPreview.js
src/components/social.js
src/pages/index.js
src/utils/workflows.js

PR for https://github.com/rahuldkjain/github-profile-readme-generator/issues/80

Support to dynamically add blogs from personal website

---

src/components/markdown.js
src/components/markdownPreview.js

fix that won't hide HTML in top skills

[fix]: issue #90

---

README.md

Fixed 16 spelling and grammar issues in the Readme

Fixed spelling and grammar in the Readme

---

README.md
src/components/donate.js
src/markdown-pages/support.md
src/pages/index.js

[add]: donate below markdown-box

---

src/components/skills.js

Left-aligned titles gets more attraction from the user.

fix: #158 aligns titles to the left

---

src/constants/skills.js

@rahuldkjain I am creating this PR in response to issue #184  assigned to me.
Please go through it and suggest any required changes.

Created a new category of Game Engines and added Unity to it

---

src/pages/index.js

Added basic validation before readme generation

Update file with twitterBadge in const data

---

src/components/addons.js
src/components/donate.js
src/components/markdownPreview.js
src/pages/index.js

Resolves #146 
Wrapped emojis in span, changed some `div`s which had button role to actual `button` elements and added `rorefferer` `rel` to some `a` tags.
Do tell me if I have to change anything 😄

Warnings resolved

---

src/constants/skills.js

Added XD in the Software Section respect to #149

Added XD respect to Issue #149

---

__mocks__/file-mock.js
__mocks__/gatsby.js
jest-preprocess.js
jest.config.js
loadershim.js
package-lock.json
package.json
src/components/__tests__/__snapshots__/title.test.js.snap
src/components/__tests__/title.test.js

**Description**
- Add and configure Jest and other related dependencies to start implementing unit tests.
- Add basic unit test for the `Title` component.
**Related issue**: #47 
**References**
- https://www.gatsbyjs.com/docs/unit-testing/ (Mainly followed this instruction step by step)
- https://github.com/gatsbyjs/gatsby/tree/master/examples/using-jest
- https://jestjs.io/docs/en/snapshot-testing.html
**Note:**
- The directory structure is the recommended one in the above links. Thought of moving the three extra files (except `jest.config.js`) as they crowd the root folder a bit but I didn't want to deviate from the recommended structure much.
- [Jest recommends committing snapshot files](https://jestjs.io/docs/en/snapshot-testing.html#should-snapshot-files-be-committed).
Awaiting …

testing: #47 Add unit tests

---

src/constants/skills.js

Resolves #227. I've added the SVG icon that I found on the [Wappalyzer public repository](https://github.com/AliasIO/wappalyzer/tree/master/src/drivers/webextension/images)

Add VuePress as a static site generator

---

.github/PULL_REQUEST_TEMPLATE.md

[add]: pr-template

---

src/constants/skills.js

Fixed broken link for cockroachdb icon
Fixed #249 

fixed broken cockroachdb icon link

---

package.json

change gatsby-plugin-sharp version

---

src/constants/skills.js

Added Arduino and Solidworks

---

src/constants/skills.js

**Added These skills :-** 
* Game Engines :- 
- unreal: "https://unrealengine.com/",
* Static Site Generators :- 
- hexo: "hexo.io/",
- middleman: "https://middlemanapp.com/"
* Programming Languages :- 
- elixir: "https://elixir-lang.org"
- erlang: "https://www.erlang.org/",
- coffeescript: "https://coffeescript.org/",
* Mobile App Development :- 
-  apachecordova: "https://cordova.apache.org/",
* BaaS :-
-  heroku: "https://heroku.com",
* Databases :-
- "sqlite": "https://www.sqlite.org/",  
* Devops :-
-  travisci: "https://travis-ci.org",
* Softwares :- 
- postman: "https://postman.com",
* Add Automation Category and added :-
- zapier: "https://zapier.com",
*More* :- 
Also added many missing links ....
#258

add new skills

---

src/components/footer.js
src/pages/index.css

This PR fixes the footer so that it displays responsively on mobile.
#262 
[![Image from Gyazo](https://i.gyazo.com/4705a3383ee50cedda65693d1a61ce63.png)](https://gyazo.com/4705a3383ee50cedda65693d1a61ce63)
n/a

update footer to be responsive

---

package-lock.json
src/components/markdown.js
src/components/markdownPreview.js

Added a condition to show `Connect with me` title only when there is at least one social account (except github) entered.
Fixes: #261 
+ Added the condition to show the subtitle only when there is a social prop except github.
| without | with |
|---|---|
|![Screenshot from 2020-10-12 15-04-18](https://user-images.githubusercontent.com/41508422/95730713-4232f780-0c9c-11eb-8082-d50f34126dc1.png)|![Screenshot from 2020-10-12 15-03-44](https://user-images.githubusercontent.com/41508422/95730718-44955180-0c9c-11eb-9877-8bb6867f7ca4.png)|

[fix]: Conditional rendering of SectionTitles

---

CODE_STYLE_GUIDE.md

Added a code style guide which the contributors can follow.
#276 
You can view the guide [here](https://github.com/YashKandalkar/github-profile-readme-generator/blob/code-style-guide/CODE_STYLE_GUIDE.md).

added code style guide

---

src/constants/skills.js

Using source urls for SVG icons.
#278

[fix]: issue #278

---

src/constants/skills.js

Added Matlab icon
https://github.com/rahuldkjain/github-profile-readme-generator/issues/281
Current behavior:
1. Go to https://rahuldkjain.github.io/gh-profile-readme-generator
2. Scroll to software section
3. Look at the matlab icon, with no src attribute
Expected behavior
An icon (of matlab) to be shown

added matlab icon

---

src/constants/skills.js

Duplicate `coffeescript` key value pair
**icons**
https://github.com/rahuldkjain/github-profile-readme-generator/blob/1f5b37ce0d941cb09ce61446e6655b64a5f859de/src/constants/skills.js#L235
https://github.com/rahuldkjain/github-profile-readme-generator/blob/1f5b37ce0d941cb09ce61446e6655b64a5f859de/src/constants/skills.js#L427
**skillWebsites**
https://github.com/rahuldkjain/github-profile-readme-generator/blob/1f5b37ce0d941cb09ce61446e6655b64a5f859de/src/constants/skills.js#L454
https://github.com/rahuldkjain/github-profile-readme-generator/blob/1f5b37ce0d941cb09ce61446e6655b64a5f859de/src/constants/skills.js#L583

fix: duplicate coffeescript key

---

src/constants/skills.js

Add Microsoft SQL Server skill

---

src/components/footer.js

Fix margins in footer links
Solves #285 
Before:
After:

fix(footer): spacing inconsistencies

---

src/components/__tests__/__snapshots__/footer.test.js.snap
src/components/__tests__/footer.test.js

Fix https://github.com/rahuldkjain/github-profile-readme-generator/issues/296 
Using the snapshot. I was following title test sample.

Addint test for the footer

---

src/components/__tests__/__snapshots__/loader.test.js.snap
src/components/__tests__/loader.test.js

Added tests for loader component.
Related issue: https://github.com/rahuldkjain/github-profile-readme-generator/issues/298

Add loader test snapshot

---

src/components/__tests__/__snapshots__/donate.test.js.snap
src/components/__tests__/donate.test.js

Add `donate` component snapshot test.
https://github.com/rahuldkjain/github-profile-readme-generator/issues/295

Add donate snapshot test

---

src/components/__tests__/__snapshots__/header.test.js.snap
src/components/__tests__/header.test.js

Add header snapshot test
https://github.com/rahuldkjain/github-profile-readme-generator/issues/297

Add header snapshot test

---

src/components/__tests__/__snapshots__/footer.test.js.snap
src/components/__tests__/__snapshots__/markdownPreview.test.js.snap
src/components/__tests__/markdownPreview.test.js
src/components/markdownPreview.js

Issue: add unit test cases for markdownPreview component #300
IssueLink: https://github.com/rahuldkjain/github-profile-readme-generator/issues/300
Added test cases for markdownPreview component.
Related Issue: Refactoring Sub-Components in Markdown Preview Component #313
Related Issue Link: https://github.com/rahuldkjain/github-profile-readme-generator/issues/300
No functionality changed.
Not Required

Markdown preview test

---

README.md

Add new sponsors in the README.

[add]: new sponsors

---

README.md
package.json

Update package.json details and remove contributors section from README

[fix]: readme and package.json

---

.eslintrc.json
.prettierrc
package-lock.json
package.json

PR for issue #275
CC: @rahuldkjain

Added prettier and eslint config files

---

README.md
jest.config.js
src/components/footer.js
src/components/markdown.js
src/components/markdownPreview.js
src/components/support.js
src/constants/defaults.js
src/pages/index.js

Add BuyMeACoffee in Support section

[add]: buymeacoffee support

---

src/constants/skills.js

changed the cdn links of the icons

---

src/components/__tests__/__snapshots__/donate.test.js.snap
src/components/donate.js

Fixed Broken Paypal Icon 
PayPal icon link broken #365

fix paypal icon

---

src/components/donate.js

[fix]: paypal-icon

---

src/constants/skills.js

Adds [Angular 2+](https://angular.io/) as a skill under Frontend Development and website link.
Related to #373

Add Angular 2+ icon, link

---

src/components/__tests__/__snapshots__/markdown.test.js.snap
src/components/__tests__/__snapshots__/markdownPreview.test.js.snap
src/components/__tests__/markdown.test.js
src/components/__tests__/markdownPreview.test.js

Fixes #369
Changed `regulary` -> `regularly` as it's a typo.

Fixes #369 - incorrect spelling

---

CODE_STYLE_GUIDE.md
README.md
src/markdown-pages/about.md

Just fixing a few typos found in the docs!

docs: fix typos

---

src/components/markdown.js

fixed social icons

---

src/components/markdown.js
src/components/markdownPreview.js
src/components/support.js

- [* ] Feature
Updated support.js to give an option to user for adding his Ko-fi donation address. 
Updated markdown.js and markdownPreview.js for accepting Ko-fi donation. 
This Pull Request fixed the issue #424

Added Ko-fi donation option

---

.travis.yml
src/components/addons.js
src/components/header.js
src/components/markdown.js
src/components/markdownPreview.js

fix: few ESLint warnings

---

.eslintrc.json
.prettierrc
CODE_STYLE_GUIDE.md
__mocks__/gatsby.js
src/components/__tests__/addons.test.js
src/components/__tests__/donate.test.js
src/components/__tests__/markdown.test.js
src/components/__tests__/markdownPreview.test.js
src/components/addons.jsx
src/components/donate.jsx
src/components/footer.jsx
src/components/header.jsx
src/components/markdown.jsx
src/components/markdownPreview.jsx
src/components/skills.jsx
src/components/social.jsx
src/components/subtitle.jsx
src/components/support.jsx
src/components/title.jsx
src/components/work.jsx
src/constants/skills.js
src/html.jsx
src/pages/index.jsx
src/utils/link-generators.js
src/utils/workflows.js

fix: linting errors
